# Generated by Django 5.0.2 on 2024-02-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="platform",
        ),
    ]
